### ISSUE TITLE
Separate Number of Searches for Mobile

### ISSUE THREAD

**Issue by jef1296** [mikeyaworski/ABS#17]
Hi, is there a way you could add a different amount of search for mobile searches, for example when choosing "desktop and mobile spoofing" : 35 desktop searches and 20 mobile searches, instead of only one number of searches for both.

**Comment by mikeyaworski** [comment]
I'll think about how to do this nicely, but it's just that I don't want to have too many inputs on the UI. I'm open to UI suggestions here as well. Otherwise I'll get to this at some point.

**Comment by jef1296** [comment]
No problem I was just wondering, since you usually only need 100 points for mobile by adding a separate input it would take less time to do the searches.

**Comment by Snakejke351980** [comment]
[Td]() #

[codecov.yml
