### ISSUE TITLE
Thanks, plus some ideas...

### ISSUE THREAD

**Issue by mike15623** [mikeyaworski/ABS#18]
Thanks for working on this!

1. Unfocused activity
2. Ability to make additions to the search dictionary
3. Scheduling/automatic activity

**Comment by mikeyaworski** [comment]
My pleasure.

Regarding the feedback (mostly notes for myself to look at later when implementing):

1. For unfocused activities, we can probably send the search parameters to the background script in a message with some tab ID (current tab at the time that you start searches) and then perform searches from the background script (using that tab ID for changing href).
2. Although this would be too much UI for the popup, we can add a full size options page and allow them to enter their own search queries to pool from on there.
3. This might be an overreaching / invasive feature. More research can be done into this, though. Off the top of my head, if the user can provide a scheduled time to perform the searches (full size options page), maybe the background script can open a new tab on the scheduled time and start the searches there.

**Comment by mikeyaworski** [comment]
I've created three separate tickets for each of the suggestions, so I'll close this issue and each of the suggestions can be tracked individually.

- https://github.com/mikeyaworski/ABS/issues/19
- https://github.com/mikeyaworski/ABS/issues/20
- https://github.com/mikeyaworski/ABS/issues/21

1 and 2 are actually complete and I'm just testing it on my local machine before pushing out a new version. It's a large refactor, so I'll do my best to make sure there are no bugs.
