### ISSUE TITLE
Bitcoin donation address?

### ISSUE THREAD

**Issue by mike15623** [mikeyaworski/ABS#25]
As an alternative to the “buy me a coffee”, do you have a bitcoin donation address?

If you’re not interested just let me know! 😉

Thanks for your work!

**Comment by mikeyaworski** [comment]
Oh interesting idea. I may add this above/beside the coffee button at some point.

But yes, this is my bitcoin address:

```
3Cc3CmCbyzMu8g8zZSxAdRJydAyURGrWH7
```

> Thanks for your work!

Happy to do it! Thanks for contributing your ideas as well.

**Comment by mike15623** [comment]
Look into the bitpay api.

**Comment by mikeyaworski** [comment]
Thanks for the donation!

> Look into the btcpay api.

Will do. I'll keep this issue open until I look into that.
