### ISSUE TITLE
Can ABS be used in other search engines?

### ISSUE THREAD

**Issue by akang1937** [mikeyaworski/ABS#31]
Can ABS be used in other search engines?If not, how should it be modified so that it can be used in other search engines?

**Comment by mikeyaworski** [comment]
Yes, it can be. You would just need to change the following search:

https://github.com/mikeyaworski/ABS/blob/0418a3540682b8aec9092d491879c0426e30daee/src/background/search.js#L80-L82

It can be `https://google.com/search?q={query}`.

What would be the usefulness of this?

**Comment by ShintoPlasm** [comment]
I can imagine this being useful in other search engines which donate to charities: e.g. Ecosia, Givero...

**Comment by mikeyaworski** [comment]
I have two reservations that idea:

1. It doesn't benefit the user of the extension to do that.
2. I think that's even more unethical than the current implementation. Effectively, you'd be taking money from the companies advertising their product and donating it instead. It doesn't really sit right with me.

**Comment by ShintoPlasm** [comment]
I don't necessarily agree with the use case scenario, to be honest. It seems similar to what an extension like AdNauseam does with regular ads.
