### ISSUE TITLE
Schedule Tasks

### ISSUE THREAD

**Issue by Purpl3-Bl4ck** [mikeyaworski/ABS#32]
Could you add the schedule to automatically complete tasks?

However your extension is excellent compliments.

**Comment by mikeyaworski** [comment]
Thanks for the suggestion! Yes, this is actually being worked on 👍

**Comment by mikeyaworski** [comment]
https://github.com/mikeyaworski/ABS/commit/2c7e68a534abe7d480031dfd1a523b9fa98dfe51
