### ISSUE TITLE
Ecosia /alt search engine preferences

### ISSUE THREAD

**Issue by Alchemist22-MOG** [mikeyaworski/ABS#39]
any chance you'd be willing to add the ability to utilize alternate search engines as our automated base? Trying to use Ecosia for my queries but it looks like Bing is our only option..

**Comment by mikeyaworski** [comment]
Yup. I had a discussion about that in #33. I'll get to this in the coming weeks. The thread is a bit confusing to read, but here is the relevant comment with my response:

https://github.com/mikeyaworski/ABS/issues/33#issuecomment-729111797
