### ISSUE TITLE
Finish "This or That" quizzes automatically

### ISSUE THREAD

**Issue by bbzlazer** [mikeyaworski/ABS#40]
If not already implemented, there should be a way to finish "this or that" quizzes automatically

I have already found out how to automatically retrieve the correct answer

I do not know, however, how to make the plugin click the correct answer

(also I know little to zero javascript)

**Comment by mikeyaworski** [comment]
Sure! If there's a way to automatically retrieve the correct answer, I will implement that as an option. In the past, it's sometimes patched and just impossible to get the value from the DOM.

Please let me know your method and I'll verify.

**Comment by bbzlazer** [comment]
I haven't tried this yet, but I will report here if I gather any more information.

What I've gathered is that 

1. There is a table called `t`, it stores multiple entries such as `isWOTQuizType`, `correctAnswer`, and `inRewardsMode`. `t.correctAnswer` stores the correct answer from a hash. The hashing function is called `lr`, and it appears to hash the `data-option` value.

**Comment by mikeyaworski** [comment]
Oh nice. Well I already have the functionality in place to check against `correctAnswer` because this is what used to work. If the value stored there is indeed the result of hashing the option with `lr`, then this will be easy to do.

I'll give this a shot in the coming weeks when I have some time to spend closing out issues on this repo.

**Comment by bbzlazer** [comment]
Here's the function because it may have a different name 
`function lr(n) {
    for (var r, t = 0, i = 0; i < n.length; i++) t += n.charCodeAt(i);
    return r = parseInt(_G.IG.substr(_G.IG.length - 2), 16), t += r, t.toString()
}`

**Comment by bbzlazer** [comment]
Tested 3 times with success each time.

**Comment by mikeyaworski** [comment]
Great work! Tested it myself and also works. I'll make an update for this.

**Comment by bbzlazer** [comment]
Hmm it says `window._w.lr` is not a function

**Comment by mikeyaworski** [comment]
I'm testing on a pretty old this/that quiz. Mind linking me to the quiz you're testing on? I can add multiple fallbacks as well (the last fallback can be a manual definition).

**Comment by bbzlazer** [comment]
I just copied the whole HTML text of one of the This or That challenges. Not sure if it appears in the source

**Comment by mikeyaworski** [comment]
Gotcha. Yeah I was hoping this would be attached to the window somewhere, but since it's not, we'll just have to define it manually. Not a big deal, but will have to update it if they ever change the hash function.

**Comment by bbzlazer** [comment]
Thanks for this
