### ISSUE TITLE
Automatically complete all tasks

### ISSUE THREAD

**Issue by bbzlazer** [mikeyaworski/ABS#42]
If we already have the needed code to complete tasks when their given window is open, is it possible to just open the rewards page at a given time daily and click all the task buttons?

**Comment by mikeyaworski** [comment]
Yes. That's already available with the bottom option here:

![image](https://user-images.githubusercontent.com/10966214/103604628-a6520a00-4edf-11eb-8470-83a44a7f1a32.png)

`Open reward tasks on schedule`
