### ISSUE TITLE
 I think it's not working D:

### ISSUE THREAD

**Issue by dodiszxd** [mikeyaworski/ABS#53]
I used it and it works perfectly, but stopped counting the points after quizzes D:

**Comment by mikeyaworski** [comment]
Can you describe the issue more? You don't get the points that you're supposed to get for completing the quiz? Or are you talking about search points?

**Comment by dodiszxd** [comment]
After finishing the survey the points are not added to the account, like the quiz is done 50/50 but does not save the points in the account

**Comment by mikeyaworski** [comment]
Are you using a VPN? I'm noticing the same issue when I'm on my VPN, because it's giving me the wrong quizzes on the rewards page.

Also is it just that one quiz or is it all the quizzes / rewards?

**Comment by dodiszxd** [comment]
yeah im using vpn, all quizzes / rewards  :/

**Comment by mikeyaworski** [comment]
Hmm, well unfortunately, it looks like the rewards page is just showing incorrect quizzes while on a VPN and it doesn't look like there's a way to fix this.

Maybe something will change in the future. But in the meantime, you can avoid pressing the "Open Reward Tasks" button and instead click your points at the top right of the screen on the search page. That popup might show the real quizzes that you need to complete.

**Comment by dodiszxd** [comment]
Oh, thank you sir, i really admire your work, it has helped me a lot :)

**Comment by mikeyaworski** [comment]
Happy to help!
