### ISSUE TITLE
Random autogenerated queries occurring even though checkbox is not ticked on

### ISSUE THREAD

**Issue by sunk818** [mikeyaworski/ABS#57]
Just on one of my instances of Chrome, the "random automated queries" is occurring even though that option is not turned on. The other instances on different computers seem to be working okay. Do you know how I can completely wipe the extension for that one computer? Maybe something got corrupted locally that I need to reset?

**Comment by mikeyaworski** [comment]
This will happen if the extension cannot fetch Google Daily Trend queries. I just looked at logs and there are an insane number of requests going on, so that instance of Chrome probably has to fall back to default queries since the service is rate limited. I'll try to address that.

**Comment by mikeyaworski** [comment]
Okay, have updated the server config and the Chrome extension shouldn't get rate limited anymore. Let me know if you still have issues after closing your browser (all tabs) and reopening it.

**Comment by mikeyaworski** [comment]
Actually this will continue to be an issue until I can figure out a solution. Google is actually rate limiting the server, which makes sense. Will need to see if I can get away with not using a CORS anywhere server, or at least cache the daily trends in another server and pull from there instead (so minimal requests are going to Google).
