### ISSUE TITLE
10 Question Quiz not working

### ISSUE THREAD

**Issue by SilentSpartan** [mikeyaworski/ABS#59]
As title says. I use the extension every day but today it is not doing the quiz, even after click one answer.

**Comment by mikeyaworski** [comment]
Would you mind posting a screenshot of the quiz? Given that I'm from Canada, I don't get the same quizzes as those in the US.

**Comment by SilentSpartan** [comment]
https://i.imgur.com/yqkpHX4.png
https://i.imgur.com/OZzA5a5.png

**Comment by mikeyaworski** [comment]
Thanks for letting me know!
